services:
  tests:
    build:
      context: .
      target: base
    image: twocaptcha-tests:smoke
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: ["/bin/bash"]

  e2e:
    build:
      context: .
      target: e2e
    image: twocaptcha-tests:e2e
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
